// [Script] key_to_ascii
// [Purpose] get a character which is generated by the specified combination of keys.
// [Input]
//  argument0 : key code (e.g. ord('1'))
//  argument1 : whether the shift key is pressed or not.
// [Return value]
//  Returns a character. (When no character is generated, returns an empty string '')
// [Examples]
//  key_to_ascii(ord('1'), true) returns "!", while key_to_ascii(ord('1'), false) returns "1"
//  key_to_ascii(ord('8'), true) will return either "*" or "(", depending on the keyboard layout.
//  key_to_ascii(vk_f1, false) will result in an empty string "".
global.__KeyToAscii__ = external_define('KeyName.dll', 'KeyToAscii', dll_stdcall, ty_string, 2, ty_real, ty_real);
// Call the DLL interface.
return external_call(global.__KeyToAscii__, argument0, argument1);
